### PR TITLE
Allow rift explorer to use a swagger-enabled league client without having to restart it

### PR DESCRIPTION
**Pull request by Morilli**
pls don't make me do this again

### CODE REVIEW

**Comment by RayZz-** [comment]
I'm fine with this being merged.

**Comment by RayZz-** [comment]
I'm okay for this PR we can merge it unless @Pupix has an issue with it.

**Comment by Pupix** [comment]
LGTM

**Comment by RayZz-** [comment]
Alright I'll go ahead with the merge.

**Pull request merged**
